import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });


export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* Navbar ----- */}
        <nav className="bg-blue-100">
          <h2>Navbar</h2>
        </nav>
        {/* Children that comming from home file means page.js root file */}
        {children}
        {/* Footer ----- */}
        <footer>
          <h2 className="bg-blue-100">Footer</h2>
        </footer>
      </body>
    </html>
  );
}
